<a href="https://www.kaggle.com/code/bishaladhikari07/road-accident-regression?scriptVersionId=268401027" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/playground-series-s5e10/sample_submission.csv
/kaggle/input/playground-series-s5e10/train.csv
/kaggle/input/playground-series-s5e10/test.csv

In [2]:
df_train=pd.read_csv('/kaggle/input/playground-series-s5e10/train.csv')
df_train.head()

,id,road_type,num_lanes,curvature,speed_limit,lighting,weather,road_signs_present,public_road,time_of_day,holiday,school_season,num_reported_accidents,accident_risk
0,0,urban,2,0.06,35,daylight,rainy,False,True,afternoon,False,True,1,0.13
1,1,urban,4,0.99,35,daylight,clear,True,False,evening,True,True,0,0.35
2,2,rural,4,0.63,70,dim,clear,False,True,morning,True,False,2,0.30
3,3,highway,4,0.07,35,dim,rainy,True,True,morning,False,False,1,0.21
4,4,rural,1,0.58,60,daylight,foggy,False,False,evening,True,False,1,0.56

In [3]:
df_train.shape

(517754, 14)

In [4]:
df_test=pd.read_csv('/kaggle/input/playground-series-s5e10/test.csv')
df_test.head()

,id,road_type,num_lanes,curvature,speed_limit,lighting,weather,road_signs_present,public_road,time_of_day,holiday,school_season,num_reported_accidents
0,517754,highway,2,0.34,45,night,clear,True,True,afternoon,True,True,1
1,517755,urban,3,0.04,45,dim,foggy,True,False,afternoon,True,False,0
2,517756,urban,2,0.59,35,dim,clear,True,False,afternoon,True,True,1
3,517757,rural,4,0.95,35,daylight,rainy,False,False,afternoon,False,False,2
4,517758,highway,2,0.86,35,daylight,clear,True,False,evening,False,True,3

In [5]:
df_test.shape

(172585, 13)

In [6]:
df=pd.concat([df_train,df_test],ignore_index=True)
df.shape

(690339, 14)

In [7]:
df.isna().sum()

id                             0
road_type                      0
num_lanes                      0
curvature                      0
speed_limit                    0
lighting                       0
weather                        0
road_signs_present             0
public_road                    0
time_of_day                    0
holiday                        0
school_season                  0
num_reported_accidents         0
accident_risk             172585
dtype: int64

In [8]:
df_train.shape

(517754, 14)

In [9]:
df_train.isna().sum()

id                        0
road_type                 0
num_lanes                 0
curvature                 0
speed_limit               0
lighting                  0
weather                   0
road_signs_present        0
public_road               0
time_of_day               0
holiday                   0
school_season             0
num_reported_accidents    0
accident_risk             0
dtype: int64

In [10]:
df_test.isna().sum()

id                        0
road_type                 0
num_lanes                 0
curvature                 0
speed_limit               0
lighting                  0
weather                   0
road_signs_present        0
public_road               0
time_of_day               0
holiday                   0
school_season             0
num_reported_accidents    0
dtype: int64

In [11]:
df.head()

,id,road_type,num_lanes,curvature,speed_limit,lighting,weather,road_signs_present,public_road,time_of_day,holiday,school_season,num_reported_accidents,accident_risk
0,0,urban,2,0.06,35,daylight,rainy,False,True,afternoon,False,True,1,0.13
1,1,urban,4,0.99,35,daylight,clear,True,False,evening,True,True,0,0.35
2,2,rural,4,0.63,70,dim,clear,False,True,morning,True,False,2,0.30
3,3,highway,4,0.07,35,dim,rainy,True,True,morning,False,False,1,0.21
4,4,rural,1,0.58,60,daylight,foggy,False,False,evening,True,False,1,0.56

In [12]:
df['num_lanes'].value_counts()

num_lanes
1    174647
2    173447
4    172149
3    170096
Name: count, dtype: int64

In [13]:

df['holiday'].value_counts()

holiday
True     347813
False    342526
Name: count, dtype: int64

In [14]:
df.shape
# (517754, 14)
# 690339

(690339, 14)

In [15]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn import tree
from sklearn.neighbors import KNeighborsRegressor

binaryCol=['road_signs_present','public_road','holiday','school_season']

for col in binaryCol:
    df[col]=df[col].map({True:1,False:0})

In [16]:
df.head()

,id,road_type,num_lanes,curvature,speed_limit,lighting,weather,road_signs_present,public_road,time_of_day,holiday,school_season,num_reported_accidents,accident_risk
0,0,urban,2,0.06,35,daylight,rainy,0,1,afternoon,0,1,1,0.13
1,1,urban,4,0.99,35,daylight,clear,1,0,evening,1,1,0,0.35
2,2,rural,4,0.63,70,dim,clear,0,1,morning,1,0,2,0.30
3,3,highway,4,0.07,35,dim,rainy,1,1,morning,0,0,1,0.21
4,4,rural,1,0.58,60,daylight,foggy,0,0,evening,1,0,1,0.56

In [17]:
df_train=df[:517754]
df_test=df[517754:]

In [18]:
df_train_x=df_train.drop(['accident_risk'],axis=1)
# df_train_x.head()
df_train_y=df_train['accident_risk']
df_train_y.head()

0    0.13
1    0.35
2    0.30
3    0.21
4    0.56
Name: accident_risk, dtype: float64

In [19]:
df_test_x=df_test.drop(['accident_risk'],axis=1)
df_test_x.head()

,id,road_type,num_lanes,curvature,speed_limit,lighting,weather,road_signs_present,public_road,time_of_day,holiday,school_season,num_reported_accidents
517754,517754,highway,2,0.34,45,night,clear,1,1,afternoon,1,1,1
517755,517755,urban,3,0.04,45,dim,foggy,1,0,afternoon,1,0,0
517756,517756,urban,2,0.59,35,dim,clear,1,0,afternoon,1,1,1
517757,517757,rural,4,0.95,35,daylight,rainy,0,0,afternoon,0,0,2
517758,517758,highway,2,0.86,35,daylight,clear,1,0,evening,0,1,3

In [20]:
# speed_limit,,road_type,lighting,weather,time_of_day --categorical


# curvature,num_reported_accidents,num_lanes --numerical


# road_signs_present,public_road,holiday,school_season -binary

In [21]:


numerical_col=['curvature','num_reported_accidents','num_lanes']

categorical_features=["speed_limit","road_type","lighting","weather","time_of_day"]

preprocessor=ColumnTransformer([
    ('cat',OneHotEncoder(),categorical_features),
    ('num',StandardScaler(),numerical_col)
],remainder='passthrough')



tree_models={
    'RFMODEL':Pipeline([
        ('preprocessor',preprocessor),
        ('model',RandomForestRegressor())
    ]),
    'XGBModel':Pipeline([
        ('preprocessor',preprocessor),
        ('model',XGBRegressor())
    ]),
    'DecisionTree':Pipeline([
        ('preprocessor',preprocessor),
        ('model', tree.DecisionTreeRegressor())
    ]),
        'KneighborModel':Pipeline([
        ('preprocessor',preprocessor),
        ('model', KNeighborsRegressor())
    ])
}

In [22]:
df_test.head()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,id,road_type,num_lanes,curvature,speed_limit,lighting,weather,road_signs_present,public_road,time_of_day,holiday,school_season,num_reported_accidents,accident_risk
517754,517754,highway,2,0.34,45,night,clear,1,1,afternoon,1,1,1,NaN
517755,517755,urban,3,0.04,45,dim,foggy,1,0,afternoon,1,0,0,NaN
517756,517756,urban,2,0.59,35,dim,clear,1,0,afternoon,1,1,1,NaN
517757,517757,rural,4,0.95,35,daylight,rainy,0,0,afternoon,0,0,2,NaN
517758,517758,highway,2,0.86,35,daylight,clear,1,0,evening,0,1,3,NaN

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690339 entries, 0 to 690338
Data columns (total 14 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      690339 non-null  int64
 1   road_type               690339 non-null  object
 2   num_lanes               690339 non-null  int64
 3   curvature               690339 non-null  float64
 4   speed_limit             690339 non-null  int64
 5   lighting                690339 non-null  object
 6   weather                 690339 non-null  object
 7   road_signs_present      690339 non-null  int64
 8   public_road             690339 non-null  int64
 9   time_of_day             690339 non-null  object
 10  holiday                 690339 non-null  int64
 11  school_season           690339 non-null  int64
 12  num_reported_accidents  690339 non-null  int64
 13  accident_risk           517754 non-null  float64
dtypes: float64(2), int64(8), object(4)
memory usage: 73.7+ MB

In [24]:
from sklearn.model_selection import cross_val_score, train_test_split, cross_val_predict


X_train,X_test,y_train,y_test=train_test_split(df_train_x,df_train_y,test_size=0.2,random_state=42)

In [25]:
# from sklearn.metrics import mean_squared_error, r2_score

# for name, model_pipeline in tree_models.items():
    
#     print(f"\n=== {name} ===")
    
#      # Fit the pipeline on training data
#     model_pipeline.fit(X_train, y_train)
    
# #     # Predictions
#     y_pred = model_pipeline.predict(X_test)
    

#     mse = mean_squared_error(y_test, y_pred)
#     r2 = r2_score(y_test, y_pred)
#     print("Test MSE:", mse)
#     print("Test R2:", r2)
    
    
#      # Optional: cross-validation score for more robust metric
#     scores = cross_val_score(model_pipeline, df_train_x, df_train_y, cv=5, scoring='r2')
#     print("5-fold CV Accuracy:", scores.mean())

In [26]:

from sklearn.linear_model import LinearRegression,Ridge,BayesianRidge

non_tree_models={
    'LRMODEL':Pipeline([
        ('preprocessor',preprocessor),
        ('model',LinearRegression())
    ]),
    'RIDGEModel':Pipeline([
        ('preprocessor',preprocessor),
        ('model',Ridge())
    ]),
    'BRModel':Pipeline([
        ('preprocessor',preprocessor),
        ('model',BayesianRidge())
    ])
 
}

In [27]:
# for name,model_pipeline in non_tree_models.items():
#     print(f'model:{name}')
#     NTModel=model_pipeline.fit(X_train,y_train)
#     y_preds=NTModel.predict(X_test)
#     print('noremal score',NTModel.score(X_test,y_test))
#     mse = mean_squared_error(y_test, y_pred)
#     r2 = r2_score(y_test, y_pred)
#     print("Test MSE:", mse)
#     print("Test R2:", r2)
    
    
#      # Optional: cross-validation score for more robust metric
#     scores = cross_val_score(model_pipeline, df_train_x, df_train_y, cv=5, scoring='r2')
#     print("5-fold CV Accuracy:", scores.mean())

In [28]:
from sklearn.model_selection import GridSearchCV

params_grid={
    'model__n_estimators':[100,200,300],
    'model__max_depth':[3,5,7],
    'model__learning_rate':[0.01,0.1,0.3],
    'model__subsample':[0.8,1.0],
    'model__colsample_bytree':[0.8,1.0]
}

grid_search=GridSearchCV(tree_models['XGBModel'],params_grid,cv=3,scoring='r2',n_jobs=-1)

grid_search.fit(X_train,y_train)
print("Best Parameters:", grid_search.best_params_)
print("Best CV Accuracy:", grid_search.best_score_)

Best Parameters: {'model__colsample_bytree': 1.0, 'model__learning_rate': 0.1, 'model__max_depth': 7, 'model__n_estimators': 100, 'model__subsample': 0.8}
Best CV Accuracy: 0.8861806470758896

In [29]:
finalModel=grid_search.best_estimator_
finalModel.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat', OneHotEncoder(),
                                                  ['speed_limit', 'road_type',
                                                   'lighting', 'weather',
                                                   'time_of_day']),
                                                 ('num', StandardScaler(),
                                                  ['curvature',
                                                   'num_reported_accidents',
                                                   'num_lanes'])])),
                ('model',
                 XGBRegressor(base_score=None, booster=None, callbacks=None,
                              colsample_bylevel=None, colsamp...
                              feature_types=None, gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=0.1,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=7, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=100, n_jobs=None,
                              num_parallel_tree=None, random_state=None, ...))])

In [30]:
finalModel.score(X_test,y_test)

0.8853041858917462

In [31]:
y_pred=finalModel.predict(X_test)

In [32]:
from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print("Test MSE:", mse)
print("Test R2:", r2)

Test MSE: 0.003167003100485746
Test R2: 0.8853041858917462

In [33]:
submission=pd.DataFrame({
    "id":df_test['id'],
    "accident_risk":finalModel.predict(df_test_x)
})
print(submission)
submission.to_csv('submission.csv',index=False)
submission.head(2)

            id  accident_risk
517754  517754       0.290404
517755  517755       0.130729
517756  517756       0.191589
517757  517757       0.327135
517758  517758       0.409583
...        ...            ...
690334  690334       0.102609
690335  690335       0.517191
690336  690336       0.264023
690337  690337       0.129010
690338  690338       0.483672

[172585 rows x 2 columns]

            id  accident_risk
517754  517754       0.290404
517755  517755       0.130729